name: PR Build Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: HolyGeek404/goodstuff-templates/.github/workflows/api-pr-build-test.yml@main
    name: "PR Build"
    with:
      test-path: 'GoodStuff.ProductApi.Application.Tests/GoodStuff.ProductApi.Application.Tests.csproj'
